### ISSUE TITLE
SSR complete examples are not rendering correctly (code is missing)

### ISSUE THREAD

**Issue by VilleMiekkoja** [City-of-Helsinki/helsinki-design-system#1105]
Hello guys 👋 . Reporting a small bug regarding doc site.

SSR complete examples are not rendering correctly (code is missing):

<img width="1044" alt="image" src="https://github.com/City-of-Helsinki/helsinki-design-system/assets/2777633/2285601c-7881-463e-88ae-b5dbcc78f4b4">

**Comment by laurakarhu** [comment]
Thanks for reporting!

**Comment by laurakarhu** [comment]
Thank you, fixed in [release 3.3.0!](https://github.com/City-of-Helsinki/helsinki-design-system/releases/tag/v3.3.0)
