### ISSUE TITLE
Allow access to Button components underlying button node by supporting ref

### ISSUE THREAD

**Issue by Jokinen** [City-of-Helsinki/helsinki-design-system#124]
**Is your feature request related to a problem? Please describe.**
React offers the `ref` mechanism for communicating with the underlying DOM nodes. [The React documents recommend this mechanism for managing `focus`](https://reactjs.org/docs/refs-and-the-dom.html). In Varaamo, I was trying to alter the natural tab order on the page in order to skip content that was not accessible with keyboard. In my case, the next component after the skipped content was a button which I wanted to focus like so: `ref.current.focus()`.

**Describe the solution you'd like**
[React.forwardRef](https://reactjs.org/docs/react-api.html#reactforwardref) allows to easily manage refs. After this change I would be able to pass down a `ref` in the `ref` prop of the `Button` tag.

**Describe alternatives you've considered**
`refs` could be enabled for other components as well. Another important candidate would be `TextInput`.

**Comment by niglu1** [comment]
This will be fixed in #132
