### ISSUE TITLE
Broken Storybook link in nds-react NPM

### ISSUE THREAD

**Issue by ekantola** [City-of-Helsinki/helsinki-design-system#130]
**Describe the bug**

https://www.npmjs.com/package/hds-react link "See the components in Storybook" does not work, now points to https://city-of-helsinki.github.io/helsinki-design-system/storybook/ but should probably be https://city-of-helsinki.github.io/helsinki-design-system/storybook/core/ ?

**Comment by niglu1** [comment]
This will be fixed in #132
