### ISSUE TITLE
Checkbox component does not support a multi-row label

### ISSUE THREAD

**Issue by Jokinen** [City-of-Helsinki/helsinki-design-system#135]
**Describe the bug**
When the label of a checkbox spans multiple rows, the whitespace in the layout may be applied improperly.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start your debugging environment
2. Create a an element with a bottom margin of 20px
3. Add a checkbox after it in a manner which causes its label to span multiple rows
4. Notice that the 20px margin between the checkbox and its preceding element is not respected

**Expected behaviour**
When the checkbox label spans multiple rows, whitespace is still respected and the checkbox is aligned to the top of its container (in other words, the checkbox element and its label are "both on the first row") 

A designer asking for this alignment: https://helsinkisolutionoffice.atlassian.net/browse/HP-108?focusedCommentId=13604

**Screenshots**
<img width="617" alt="Screenshot 2020-05-14 at 9 24 29" src="https://user-images.githubusercontent.com/9090689/81900086-dbae8e00-95c4-11ea-9e79-a261a2ea86d5.png">

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: Chrome
 - Version: 81

**Comment by Jokinen** [comment]
If this is a bug, I can likely help out with is, seeing as our project needs the multilines.

**Comment by niglu1** [comment]
Yup, it was a bug. #136 should fix this issue.
