### ISSUE TITLE
Consider allowing richer content for checkbox labels

### ISSUE THREAD

**Issue by Jokinen** [City-of-Helsinki/helsinki-design-system#140]
**Is your feature request related to a problem? Please describe.**
We use the checkbox component as a control the user can use to communicate compliance with out instructions or requests. For instance, on one page we a button that allows the user to delete their profile. Before they can do that, they must tick a checkbox

<img width="520" alt="Screenshot 2020-05-18 at 16 23 20" src="https://user-images.githubusercontent.com/9090689/82218020-ec903400-9923-11ea-88b2-9b5eb2e33fb5.png">

Our designs suggest us to include links directly within the label. When I attempt to do this by using the `<Checkbox />` component in a TS project, I will face a type error. Only text is allowed for the label. This is further highlighted by the naming of the prop which controls content of the label: `labelText`.

**Describe the solution you'd like**
I would like to be able to add more rich content as a description, or label, for a checkbox, that's the type of input. More specifically, I would like to add a link within the label.

**Describe alternatives you've considered**
* Rebuild `<Checkbox />` with classes from `hds-core`
* Add 
```ts
// eslint-disable-next-line @typescript-eslint/ban-ts-ignore
// @ts-ignore
```
 to ignore error

**Additional context**
I was able to find discussion that briefly talked about the accessibility with this approach: https://github.com/FreedomScientific/VFO-standards-support/issues/76

A document is linked, but the section talking about anchors, labels and accessibility has since been removed. I was not able to confirm that an anchor within a label element does not negatively impact accessibility.

**Comment by niglu1** [comment]
Yes, this should definitely be supported. I'll try to include this in the alpha release next week.
