### ISSUE TITLE
[FYI] Importing react components injects global styles

### ISSUE THREAD

**Issue by Jokinen** [City-of-Helsinki/helsinki-design-system#174]
**Is your feature request related to a problem? Please describe.**
When a component is imported from `hds-react`, some global styles are also injected. These, among other things, set header styles. As an example, when the consumer of the component library imports the `Notification` component, they may also inadvertently re-style all the headings in their app (hey that's me :D). Because the styles are included at the places where the component is imported, it's hard to manage for instance import order to stop HDS from overriding intended styles. The behaviour can also vary between development and production builds.

Originally I included `hds-react` in the project, because we needed a notification component which HDS happened to provide.

**Describe the solution you'd like**
Allowing components to be imported without global styles may be too difficult. If so, we are left with documentation options that vary from stating this fact, all the way to forming a better clarity on how HDS compliant a project should be before `hds-react` should be considered.

**Comment by niglu1** [comment]
I can definitely see this being an issue. The `hds-core` base styles are imported in the `hds-react` package to get access to the CSS vars among other things (like `normalize.css`). The global styles you mentioned are included in those imported styles. Those styles can be safely removed on our part, but it could be a breaking change for someone else using the package. Still, we'll be removing them in a future release. Thanks for bringing this up!

**Comment by niglu1** [comment]
Fixed in #199
