### ISSUE TITLE
How to deal with CSS specificity changing between local development builds and production builds in a CRA based application?

### ISSUE THREAD

**Issue by Jokinen** [City-of-Helsinki/helsinki-design-system#195]
## Question
In the local build, our project specific styles are applied with `<style>` tags in the `<head>` of the HTML document. In the production build they are bundled into a CSS file. When styles are applied with `<style>` tags, they take precedence over HDS styles. When they are linked from a file, HDS takes precedence.

In an un-ejected CRA application, do we have any strategies to make it more likely that specificity is static between the builds?

Generally, I was a bit surprised to find out that HDS styles do not get bundled in production. What would it take to get them bundled--can we even make that happen? Are we missing something in our configuration? It looks like the normalizr and CSS variables are bundled, but the component specific CSS is not. I have some hope that CRA would know to order the vendor bundle before our project styles, which could resolve this question.

## Additional context
Here's an example scenario where we faced this issue.

We refactored one of our buttons from a custom implementation to that of HDS. The view itself predates HDS and as such has a colour scheme that's not compatible with default button colours. To resolve this, we had to override the default button background colour.

We did this by adding a custom `className` to the button. The project uses CSS modules. Within that selector, we set the background colour of the button to something else than it's by default.

Locally our custom style takes precedence over HDS ones. I didn't get down to the nitty gritty of it, but by glance it seems that this is because in the local development build, styles are applied with `<style>` tags inside `<head>`--just like with HDS.

However, in the "production" build, our custom style gets bundles into a CSS file. This file is linked to the document before HDS's inline styles. In this scenario HDS styles end up taking precedence.

This is of course not optimal, because it deteriorates the trust a dev can have for the local build and increases the chance of introducing bugs. In our case this is further complicated by the fact that review builds of the application are hardly ever used, because they need manual configuration that only two people can do.

**Comment by badrange** [comment]
This happened to me too today. I work around it by adding a lovely !important to the CSS rule. Yuk.

**Comment by lehtoinen** [comment]
Instead on `!important`, I recommend bumping up the selector specificity with self-chaining classes.

For example:
```
.myCustomClass.myCustomClass {
  ...
}
```
... will usually be enough to bump up the specificity enough to have the custom style take over the HDS classes.

**Comment by badrange** [comment]
That is a much better workaround.
