### ISSUE TITLE
Multiselect dropdown retains focus styles

### ISSUE THREAD

**Issue by Sartonon** [City-of-Helsinki/helsinki-design-system#205]
## Describe the bug
Multiselect dropdown retains focus styles after blur

## How to reproduce
1. Go to [https://hds.hel.fi/storybook/react/?path=/story/components-dropdown--controlled](url)
2. Focus multiselect dropdown with TAB
3. Use up and down arrow keys no navigate items
4. Focus out with tab

## Expected behavior
Focus style should be hidden when dropdown input is blurred

## Screenshots
<img width="507" alt="Screenshot 2020-07-06 at 12 15 59" src="https://user-images.githubusercontent.com/15219142/86577815-7dc67300-bf83-11ea-945d-268e932745ba.png">

**Comment by niglu1** [comment]
This issue is fixed in #222
