### ISSUE TITLE
"Not wrapped in act(...)"-error in accessibility test with multiple Select-components

### ISSUE THREAD

**Issue by petrutsi** [City-of-Helsinki/helsinki-design-system#360]
## Describe the bug
When rendering more than one Select-components Jest Axe accessibility test gives an error:
```
console.error
    Warning: An update to Select inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */   
```

## How to reproduce
In `Select.test.tsx` the problem may be reproduced along these lines
```
const getWrapperForTwoSelects = (props?: unknown) =>
  render(
    <>
      <Select {...defaultProps} {...props} />
      <Select {...defaultProps2} {...props} />
    </>,
  );

...

describe('<Select /> spec', () => {
  it('should not have basic accessibility issues', async () => {
    const { container } = getWrapperForTwoSelects();
    const results = await axe(container);
    expect(results).toHaveNoViolations();
  });
});
```

## Device information
**Desktop (please complete the following information)**:
>  - OS: [e.g. iOS]
> - Browser [e.g. chrome, safari]
>  - Version [e.g. 22]

**Comment by goforemikaela** [comment]
This does not seem to only affect the accessibility tests, but other tests as well.
For example, if in my test I try to do: 
```
    // Select the first status from the dropdown
    userEvent.click(screen.getByText('enrollmentStatus.tentativelyDecided'));

    // Select the second status from the dropdown
    userEvent.click(screen.getByText('enrollmentStatus.decided'));
```
I will get the "not wrapped in act" error on the ASTI Select component.

**Comment by lehtoinen** [comment]
> This does not seem to only affect the accessibility tests, but other tests as well.
> For example, if in my test I try to do:
> 
> ```
>     // Select the first status from the dropdown
>     userEvent.click(screen.getByText('enrollmentStatus.tentativelyDecided'));
> 
>     // Select the second status from the dropdown
>     userEvent.click(screen.getByText('enrollmentStatus.decided'));
> ```
> 
> I will get the "not wrapped in act" error on the ASTI Select component.

Did you try to wrap those clicks with act? The error seems legit here, since you are causing state updates with the clicks.
