### ISSUE TITLE
Add useState call to useMobile hook

### ISSUE THREAD

**Issue by valtterival** [City-of-Helsinki/helsinki-design-system#493]
## To which feature the request relates to

This request is related to the useMobile hook and the Navigation component in the 'react' package.

## What

I propose adding a `updateState();` call under `window.addEventListener('resize', updateState);` inside useMobile.tsx .

## Why

This would ensure that the `isMobile` state is up to date, when a web page using it is loaded for the first time on mobile.
Navigation item styles under navigation user would be correct.

## Related material
> Optionally, you may attach screenshots, Sketch files etc. to make your request more understandable. Also, you may provide links to similar content in other design systems.

useMobile.tsx

```js
import { useEffect, useState } from 'react';

const MOBILE_BREAKPOINT = 768;
const checkIfMobile = (): boolean => (typeof window !== 'undefined' && window.innerWidth < MOBILE_BREAKPOINT) || false;

export const useMobile = (): boolean => {
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    const updateState = () => setIsMobile(checkIfMobile());

    window.addEventListener('resize', updateState);
    updateState();

    return () => window.removeEventListener('resize', updateState);
  }, []);

  return isMobile;
};
```

https://user-images.githubusercontent.com/85603770/124589736-fe53d400-de62-11eb-8e67-60d859a1d8f7.mp4

**Comment by minevala** [comment]
Fixed in https://github.com/City-of-Helsinki/helsinki-design-system/releases/tag/v1.15.0
