### ISSUE TITLE
add data-testid to react components

### ISSUE THREAD

**Issue by hkajavafutu** [City-of-Helsinki/helsinki-design-system#596]
## What
> Add data-testid attributes to components

## Why
> Facilitates creating e2e tests

## Related material
> Optionally, you may attach screenshots, Sketch files etc. to make your request more understandable. Also, you may provide links to similar content in other design systems.

**Comment by laurakarhu** [comment]
Hi thanks for the suggestion!
At least some of the components already support using data-testid. Could you give examples of the components where the issue is exists? Or would you like to have ready attributes on every component?
