### ISSUE TITLE
Ability to pass default value to the SeachInput component

### ISSUE THREAD

**Issue by sami-juvonen** [City-of-Helsinki/helsinki-design-system#666]
## To which feature the request relates to
[HDS SearchInput component](https://github.com/City-of-Helsinki/helsinki-design-system/blob/master/packages/react/src/components/searchInput/SearchInput.tsx)

## What
Add optional prop for default value

## Why
It should be possible to pass default value to the SearchInput for example on a situtation, where the user is redirected to the search page with predefined keyword.

### Example
Search has been made on a simple form and the user is redirected to the actual search page with "hakaniemi"-keyword.

>![Screenshot 2022-02-25 at 7 41 12](https://user-images.githubusercontent.com/88421815/155660772-8f04bd8c-741b-4216-b0f4-985800897dc5.png)

Now the search has "hakaniemi"-keyword active, but the SearchInput is empty, because we don't have a way to set default value.

>![Screenshot 2022-02-25 at 7 41 40](https://user-images.githubusercontent.com/88421815/155661555-0ab04fdb-6941-470d-8ec3-7f08430be42e.png)

**Comment by minevala** [comment]
We added support for passing value to SearchInput in version [2.6.0](https://github.com/City-of-Helsinki/helsinki-design-system/releases/tag/v2.6.0). Would this solve the issue?
