### ISSUE TITLE
Duplicated words in some cookie consent translations

### ISSUE THREAD

**Issue by akikoskinen** [City-of-Helsinki/helsinki-design-system#947]
## Describe the bug

In `getContent.ts` file lines [68](https://github.com/City-of-Helsinki/helsinki-design-system/blob/d8b22c08424419c5b53e206be6dbc44fca68e802/packages/react/src/components/cookieConsent/getContent.ts#L68) and [70](https://github.com/City-of-Helsinki/helsinki-design-system/blob/d8b22c08424419c5b53e206be6dbc44fca68e802/packages/react/src/components/cookieConsent/getContent.ts#L70) the Finnish word "käytetään" is repeated twice.

## Expected behavior

Only one "käytetään" word is enough.

**Comment by NikoHelle** [comment]
Fix is in https://github.com/City-of-Helsinki/helsinki-design-system/pull/943
