### ISSUE TITLE
How to deal with different styling approaches when creating contributions?

### ISSUE THREAD

**Issue by Zeukkari** [City-of-Helsinki/helsinki-design-system#99]
I'm preparing component contributions to this project and I'm a bit confused on how to deal with different approaches to CSS. This project uses CSS modules, while the project that I'm working on uses SASS, then there's styled components which is quite popular at this moment.

I'm not sure whether I should rework my components using CSS modules approach or add SASS support to the project. Can you clarify this issue a bit?

**Comment by lehtoinen** [comment]
The minimum solution is to import the helsinki.css stylesheet from the core and to use the css variables and helper styles from there (you can use @extend for SASS or compose for CSS modules).

Does this answer your question? If not, can you please provide a use case where you feel this approach is problematic.

**Comment by Zeukkari** [comment]
This project doesn't support scss modules right and while my component candidates are all built using scss. I opened a PR for add scss support to hds-react https://github.com/City-of-Helsinki/helsinki-design-system/pull/101.

I'm trying to make up my mind whether that PR should be merged or not.

This issue affects the following PR's:

```
https://github.com/City-of-Helsinki/helsinki-design-system/pull/105
https://github.com/City-of-Helsinki/helsinki-design-system/pull/104
https://github.com/City-of-Helsinki/helsinki-design-system/pull/103
https://github.com/City-of-Helsinki/helsinki-design-system/pull/102
https://github.com/City-of-Helsinki/helsinki-design-system/pull/97
```
